# Paired end reads Sample FASTQ files of paired end reads per sample.
samples:
  BRCA1:
    r1: data/brca1/BRCA1_paired_dat1.fq
    r2: data/brca1/BRCA1_paired_dat2.fq
  TP53:
    r1: data/tp53/TP53_paired_dat1.fq
    r2: data/tp53/TP53_paired_dat2.fq

# Reference genome FASTA
reference: data/chr17/Homo_sapiens.GRCh38.dna.chromosome.17.fa

# snpEff database matching the reference genome
snpeff_genome: GRCh38.99

# Path to snpEff.jar (uv venv). With conda, set this to "" to use conda's snpEff.
snpeff_jar: ~/tools/snpEff/snpEff.jar
# Java 21 is needed for snpEff (use `which java` in bash to see which version you have)
# With conda, set this to "" as well.
snpeff_java: /opt/homebrew/opt/openjdk@21/bin/java
snpeff_memory: 8g

# Compressed dbSNP VCF file, with its .tbi index next to it
dbsnp: data/dbSNP/All_20180418_C17.gz

# Gene regions of interest, as positions in the given reference genome (in this case GRCh38)
regions:
  BRCA1:
    chrom: "17"
    start: 43044292
    end: 43170245
  TP53:
    chrom: "17"
    start: 7661779
    end: 7687546

# GATK filters for calling SNPs
snp_filters:
  QD_filter: "QD < 2.0"
  FS_filter: "FS > 60.0"
  MQ_filter: "MQ < 40.0"
  SOR_filter: "SOR > 4.0"
  MQRankSum_filter: "MQRankSum < -12.5"
  ReadPosRankSum_filter: "ReadPosRankSum < -8.0"

threads:
  bwa_mem: 8
  markduplicates: 4
  haplotypecaller: 4
